allowBuilds:
  '@coinbase/x402': set this to true or false
  '@opensea/seaport-js': set this to true or false
  bigint-buffer: set this to true or false
  bufferutil: false
  esbuild: true
  keccak: false
  opensea-js: set this to true or false
  secp256k1: set this to true or false
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
